// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb4RmjjUwOSeXeUXvgjJHEP8F-FfKnL0s',
    appId: '1:305860870103:web:987e9d1ba871f367781592',
    messagingSenderId: '305860870103',
    projectId: 'lost-things-42bf7',
    authDomain: 'lost-things-42bf7.firebaseapp.com',
    storageBucket: 'lost-things-42bf7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeVq3Iad24u0oaYMJ61o9lyiIEmZTdS3A',
    appId: '1:305860870103:android:21030d6934377cff781592',
    messagingSenderId: '305860870103',
    projectId: 'lost-things-42bf7',
    storageBucket: 'lost-things-42bf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo8mfzjVQkV8GTWwwu-KY8fgaK0UQ-7cM',
    appId: '1:305860870103:ios:d72308f4055916d9781592',
    messagingSenderId: '305860870103',
    projectId: 'lost-things-42bf7',
    storageBucket: 'lost-things-42bf7.appspot.com',
    iosBundleId: 'com.example.lostThings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo8mfzjVQkV8GTWwwu-KY8fgaK0UQ-7cM',
    appId: '1:305860870103:ios:4588a466b150aab2781592',
    messagingSenderId: '305860870103',
    projectId: 'lost-things-42bf7',
    storageBucket: 'lost-things-42bf7.appspot.com',
    iosBundleId: 'com.example.lostThings.RunnerTests',
  );
}
